### ISSUE TITLE
Please fix the error Episode #76 ~ 

### ISSUE THREAD

**Issue by sylar-Jeon** [pointfreeco/episode-code-samples#106]
Your PrimeTime example is not compile. 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/54385803/145225271-8987fd1b-6f8e-4694-8d02-b1b995d29ea6.png">

.../PrimeTime/Counter/Counter.swift:21:12: error: cannot convert value of type '(inout Int, CounterAction) -> ()' to expected argument type '(inout Int, CounterAction) -> Effect' (aka '(inout Int, CounterAction) -> () -> ()')
  pullback(counterReducer, value: \CounterViewState.count, action: \CounterViewAction.counter),
           ^
.../PrimeTime/Counter/Counter.swift:22:12: error: cannot convert value of type '(inout PrimeModalState, PrimeModalAction) -> ()' (aka '(inout (count: Int, favoritePrimes: Array<Int>), PrimeModalAction) -> ()') to expected argument type '(inout PrimeModalState, PrimeModalAction) -> Effect' (aka '(inout (count: Int, favoritePrimes: Array<Int>), PrimeModalAction) -> () -> ()')
  pullback(primeModalReducer, value: \.self, action: \.primeModal)
           ^

Xcode Version 13.1 (13A1030d)

Also you should check all episode. There are many episode examples that cannot be built.

**Comment by stephencelis** [comment]
Hi @sylar-Jeon,

Because of how often Swift and Apple's frameworks change, it isn't possible for us to update all code samples to build in the latest Xcode every release.

You should definitely be able to get each code sample to build by using the version of Xcode that we used at the time the episode was released. You can use the following web site to figure out which version of Xcode that was:

https://xcodereleases.com

We still encourage folks to try to get old code samples to build in the latest Xcode if possible. It can be frustrating, but also rewarding, and an exercise that can help in real-world maintenance of code bases over time.

**Comment by sylar-Jeon** [comment]
OK.
Thank you for your immediate feedback. 
I can fix it.
