### ISSUE TITLE
Episode 196: Runtime warning work only in half of the cases

### ISSUE THREAD

**Issue by vladvlasov256** [pointfreeco/episode-code-samples#122]
**Time**: 35:20

I've noticed that runtime warning in the `equals()` in the [File.swift](https://github.com/pointfreeco/episode-code-samples/blob/7f5b443dc4d84b22d5972c6b4a4c01ebae266e8d/0196-tca-concurrency-pt2/swift-composable-architecture/Sources/ComposableArchitecture/File.swift) is fired only if `lhs` is non-equatable.

But what if `rhs` is non-equable too? Or `rhs` is the only one which is non-equatable here.

```
public func equals(_ lhs: Any, _ rhs: Any) -> Bool {
  ...

  guard
    let lhs = lhs as? any Equatable
  else {
    runtimeWarning(
      "Tried to compare a non-equatable error type: %@",
      ["\(type(of: lhs))"]
    )
    return false
  }

  ...
}
```

IMO, a version on 34th minute with two casts is more helpful for users.

**Comment by stephencelis** [comment]
Hi @vladvlasov256,

Our episodes have to be abbreviated/draft versions of the final code, so we chose to not spend more time on that particular feature :smile:

In the current beta version of the code, we actually _do_ address this, but we've made a slightly different decision: we _only_ show the equatable warning when trying to compare two errors of the same type, since otherwise the failure will fall through to a readable diff that shows two very different types:

https://github.com/pointfreeco/swift-composable-architecture/blob/concurrency-beta/Sources/ComposableArchitecture/Effects/TaskResult.swift#L217

We made this decision to reduce noise when debugging errors, since the case of 2 different error types that both lack conformances would lead the user to be bombarded with 3 failure messages. This reduces things down to 1 failures at a given time.

If you'd like to discuss this behavior more, we have a discussion on the TCA repo for all things Concurrency Beta:

https://github.com/pointfreeco/swift-composable-architecture/discussions/1186
