### ISSUE TITLE
ForwardComposition associativity in Episode 1

### ISSUE THREAD

**Issue by ScottieLee** [pointfreeco/episode-code-samples#21]
Shouldn't the associativity of forward composition be left instead of right?
![image](https://user-images.githubusercontent.com/3660879/52109428-68d00c80-2638-11e9-8fae-4b1e02444182.png)

**Comment by stephencelis** [comment]
Ha you're right! Some early episodes had their playgrounds "re-transcribed," so this difference may have snuck in, so fixed to be consistent.

For a little more info: left vs. right associativity does not really matter for function composition, since the order in which you compose does not matter, but Swift makes us choose :)
