### ISSUE TITLE
Store shouldn't store environment

### ISSUE THREAD

**Issue by mayoff** [pointfreeco/episode-code-samples#60]
`Store.init` receives a reducer as an argument, and an environment object appropriate to that reducer. It saves the given environment in a property of type `Any`, and wraps the given reducer in a new closure that casts an `Any`-typed environment back to the appropriate type.

Instead, the closure can capture the environment with the appropriate type, and pass it to the given reducer with no casting.

Please see [this diff](https://github.com/mayoff/episode-code-samples/commit/597b411abcb3a2a7bf1647b50656d5bd4848189e?diff=split).

**Comment by mbrandonw** [comment]
Hey @mayoff, yeah this is a great change, and we even have exercises to do this in episode 91: https://www.pointfree.co/episodes/ep91-dependency-injection-made-composable#exercises

The episode method was done for ease of narrative to try to make it clear how one could erase the environment type from the store. In the open source library we are working on for the composable architecture we do things the other way.

I don't think we'll merge this since we want the episode code samples to mimic what was covered in the episodes.

Let us know if you have any questions.
